// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoLD_vTHvBVeo1zTxsyxfZU-ncBnNnD9E',
    appId: '1:171318255427:web:044d2e37b298df19ee59f6',
    messagingSenderId: '171318255427',
    projectId: 'flutter-todolist-74133',
    authDomain: 'flutter-todolist-74133.firebaseapp.com',
    databaseURL: 'https://flutter-todolist-74133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-todolist-74133.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOhyVJ2uI7iL9DE6DGhDO2oJ1PzK0Sb6Y',
    appId: '1:171318255427:android:1622a905ec1a4a85ee59f6',
    messagingSenderId: '171318255427',
    projectId: 'flutter-todolist-74133',
    databaseURL: 'https://flutter-todolist-74133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-todolist-74133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLbAL0SnupOipomsvS7GXyX34QlJVT4mk',
    appId: '1:171318255427:ios:90ac0863817179e6ee59f6',
    messagingSenderId: '171318255427',
    projectId: 'flutter-todolist-74133',
    databaseURL: 'https://flutter-todolist-74133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-todolist-74133.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLbAL0SnupOipomsvS7GXyX34QlJVT4mk',
    appId: '1:171318255427:ios:90ac0863817179e6ee59f6',
    messagingSenderId: '171318255427',
    projectId: 'flutter-todolist-74133',
    databaseURL: 'https://flutter-todolist-74133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-todolist-74133.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoLD_vTHvBVeo1zTxsyxfZU-ncBnNnD9E',
    appId: '1:171318255427:web:fde51c53dfca0e85ee59f6',
    messagingSenderId: '171318255427',
    projectId: 'flutter-todolist-74133',
    authDomain: 'flutter-todolist-74133.firebaseapp.com',
    databaseURL: 'https://flutter-todolist-74133-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-todolist-74133.firebasestorage.app',
  );
}
